Create database ST10467645_EventEase;

USE ST10467645_EventEase;

CREATE TABLE Venue (
	VenueID INT IDENTITY (1, 1) PRIMARY KEY,
	VenueName VARCHAR(100) NOT NULL,
	Location VARCHAR(150) NOT NULL,
	Capacity INT NOT NULL,
	ImageURL TEXT NOT NULL
);

CREATE TABLE Event (
	EventID INT IDENTITY (1, 1) PRIMARY KEY,
	EventName VARCHAR(100) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL
);

CREATE TABLE Booking (
	BookingID INT IDENTITY (1, 1) PRIMARY KEY,
	VenueID INT NOT NULL,
	EventID INT NOT NULL,
	BookingDate DATE NOT NULL,
	CONSTRAINT FK_Booking_Venue 
	FOREIGN KEY (VenueID) REFERENCES Venue(VenueID),
	CONSTRAINT FK_Booking_Event 
	FOREIGN KEY (EventID) REFERENCES Event (EventID)
);
