/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Question2;

import java.io.*;

import javax.swing.*;

/**
 *
 * @author lab_services_student
 */
public class Q2 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Q2.class.getName());

    /**
     * Creates new form Q2
     */
    public Q2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoad = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRpt = new javax.swing.JTextArea();
        lbYearsProcessed = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnLoad = new javax.swing.JMenuItem();
        mnSave = new javax.swing.JMenuItem();
        mnClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnLoad.setText("Load Product Data");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnSave.setText("Save Product Data");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtAreaRpt.setColumns(20);
        txtAreaRpt.setRows(5);
        jScrollPane1.setViewportView(txtAreaRpt);

        lbYearsProcessed.setText("Years Proccessed: ");

        mnFile.setText("File");

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnFile.add(mnExit);

        jMenuBar1.add(mnFile);

        jMenu2.setText("Tools");

        mnLoad.setText("Load Product Data");
        mnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoadActionPerformed(evt);
            }
        });
        jMenu2.add(mnLoad);

        mnSave.setText("Save Product Data");
        mnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveActionPerformed(evt);
            }
        });
        jMenu2.add(mnSave);

        mnClear.setText("Clear");
        mnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClearActionPerformed(evt);
            }
        });
        jMenu2.add(mnClear);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbYearsProcessed, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoad)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lbYearsProcessed)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method that loads products from memory, performs calcuations and saves it to memoy.
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed

        //Declaring and instantiating constructor object for ProductSales class.
        ProductSales ps = new ProductSales();

        //Calculating total sales.
        int totalSales = ps.getTotalSales();

        //Calculating sales over limit.
        int salesOver = ps.getSalesOverLimit();

        //Calculating sales under limit.
        int salesUnder = ps.getSalesUnderLimit();

        //Calculating the amount of years that have been proccessed.
        int proccesedP = ps.getProductsProccessed();

        //Calculating the average sales.
        double avgSales = ps.getAverageSales();

        //Displaying the data to text area.
        String rtotalSales = "Total Sales: " + totalSales + "\n";
        //Sample output for average sales shows 367 so format rounds andswer to nearest one.
        String ravgSales = "Average Sales: " + String.format("%.0f", avgSales) + "\n";
        String rsalesOver = "Sales over limit: " + salesOver + "\n";
        String rsalesUnder = "Sales under limit: " + salesUnder + "\n";

        String loadData = rtotalSales + ravgSales + rsalesOver + rsalesUnder;

        txtAreaRpt.setText(loadData);

        //Displaying the number of years proccessed in the read only label.
        lbYearsProcessed.setText("Years Proccessed: " + proccesedP);

    }//GEN-LAST:event_btnLoadActionPerformed

    //Method that saves the data loaded in the text file to a txt file.
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        //Declaring and initialising variable for data in text area.
        String loadedData = txtAreaRpt.getText();

        //If text area is empty, displays message and return.
        if (loadedData.isEmpty() || loadedData == null) {

            JOptionPane.showMessageDialog(null, "No product data to save.");

            return;

        }

        //Createing buffered writer to write to a file called data.txt and displays a success message if successful.
        try {

            BufferedWriter bw = new BufferedWriter(new FileWriter("data.txt", true));

            bw.write("Data Log\n");
            bw.write("*********************************************************\n");
            bw.write(loadedData);
            bw.write("*********************************************************\n");
            bw.close();

            JOptionPane.showMessageDialog(null, "Product Data Saved Successfully!");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    //Method to close the app when Exit menu item is selected.
    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed

        //Declaring and initialising variable for comformation to exit.
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);

        //If confirm == 0, displays message and exits app
        if (confirm == 0) {

            JOptionPane.showMessageDialog(null, "Thanks for using the app!!!");

            System.exit(0);

        }

    }//GEN-LAST:event_mnExitActionPerformed

    //Method that calls the same logic as the load product data button and its method when the menu item Load product data is selected.
    private void mnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoadActionPerformed

        btnLoad.doClick();

    }//GEN-LAST:event_mnLoadActionPerformed

    //Method that calls the same logic as the save product data button and its method when the menu item save product data is selected. 
    private void mnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveActionPerformed

        btnSave.doClick();

    }//GEN-LAST:event_mnSaveActionPerformed

    //Method that sets the text area to its default state when the clear menu item is selected.
    private void mnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClearActionPerformed

        txtAreaRpt.setText("");

        lbYearsProcessed.setText("");

    }//GEN-LAST:event_mnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Q2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbYearsProcessed;
    private javax.swing.JMenuItem mnClear;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnLoad;
    private javax.swing.JMenuItem mnSave;
    private javax.swing.JTextArea txtAreaRpt;
    // End of variables declaration//GEN-END:variables
}
